apiVersion: v1
objects:
- apiVersion: image.openshift.io/v1
  generation: 0
  image:
    dockerImageLayers: null
    dockerImageMetadata:
      ContainerConfig: {}
      Created: null
      Id: ""
      apiVersion: "1.0"
      kind: DockerImage
    dockerImageMetadataVersion: "1.0"
    metadata:
      creationTimestamp: null
  kind: ImageStreamTag
  lookupPolicy:
    local: false
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/imported-from: 172.30.1.1:5000/openshift/mysql:5.7
    creationTimestamp: null
    labels:
      app: mysql-master-slave-${INSTANCE_NAME}
    name: mysql-${INSTANCE_NAME}:5.7
  tag:
    annotations: null
    from:
      kind: DockerImage
      name: 172.30.1.1:5000/openshift/mysql:5.7
    generation: null
    importPolicy: {}
    name: "5.7"
    referencePolicy:
      type: ""
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mysql-master-slave-${INSTANCE_NAME}
    name: mysql-master-${INSTANCE_NAME}
  spec:
    replicas: 1
    selector:
      app: mysql-master-slave-${INSTANCE_NAME}
      deploymentconfig: mysql-master-${INSTANCE_NAME}
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: mysql-master-slave-${INSTANCE_NAME}
          deploymentconfig: mysql-master-${INSTANCE_NAME}
      spec:
        containers:
        - env:
          - name: MYSQL_DATABASE
            value: ${MYSQL_DATABASE}
          - name: MYSQL_MASTER_PASSWORD
            value: ${MYSQL_MASTER_PASSWORD}
          - name: MYSQL_MASTER_SERVICE_NAME
            value: mysql-master-${INSTANCE_NAME}
          - name: MYSQL_MASTER_USER
            value: ${MYSQL_MASTER_USER}
          - name: MYSQL_PASSWORD
            value: ${MYSQL_PASSWORD}
          - name: MYSQL_ROOT_PASSWORD
            value: ${MYSQL_ROOT_PASSWORD}
          - name: MYSQL_USER
            value: ${MYSQL_USER}
          image: 172.30.1.1:5000/openshift/mysql:5.7
          name: mysql-master-${INSTANCE_NAME}
          command:
            - "run-mysqld-master"
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - mysql-master-${INSTANCE_NAME}
        from:
          kind: ImageStreamTag
          name: mysql:5.7
          namespace: openshift
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mysql-master-slave-${INSTANCE_NAME}
    name: mysql-slave-${INSTANCE_NAME}
  spec:
    replicas: 1
    selector:
      app: mysql-master-slave-${INSTANCE_NAME}
      deploymentconfig: mysql-slave-${INSTANCE_NAME}
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: mysql-master-slave-${INSTANCE_NAME}
          deploymentconfig: mysql-slave-${INSTANCE_NAME}
      spec:
        containers:
        - env:
          - name: MYSQL_DATABASE
            value: ${MYSQL_DATABASE}
          - name: MYSQL_MASTER_PASSWORD
            value: ${MYSQL_MASTER_PASSWORD}
          - name: MYSQL_MASTER_SERVICE_NAME
            value: mysql-master-${INSTANCE_NAME}
          - name: MYSQL_MASTER_USER
            value: ${MYSQL_MASTER_USER}
          - name: MYSQL_PASSWORD
            value: ${MYSQL_PASSWORD}
          - name: MYSQL_ROOT_PASSWORD
            value: ${MYSQL_ROOT_PASSWORD}
          - name: MYSQL_USER
            value: ${MYSQL_USER}
          image: 172.30.1.1:5000/openshift/mysql:5.7
          name: mysql-slave-${INSTANCE_NAME}
          command:
            - "run-mysqld-slave"
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - mysql-slave-${INSTANCE_NAME}
        from:
          kind: ImageStreamTag
          name: mysql:5.7
          namespace: openshift
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mysql-master-slave-${INSTANCE_NAME}
    name: mysql-master-${INSTANCE_NAME}
  spec:
    ports:
    - name: 3306-tcp
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      app: mysql-master-slave-${INSTANCE_NAME}
      deploymentconfig: mysql-master-${INSTANCE_NAME}
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mysql-master-slave-${INSTANCE_NAME}
    name: mysql-master-lb-${INSTANCE_NAME}
  spec:
    type: LoadBalancer
    ports:
    - name: db
      port: 3306
    loadBalancerIP:
    selector:
      app: mysql-master-slave-${INSTANCE_NAME}
      deploymentconfig: mysql-master-${INSTANCE_NAME}
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mysql-master-slave-${INSTANCE_NAME}
    name: mysql-slave-lb-${INSTANCE_NAME}
  spec:
    type: LoadBalancer
    ports:
    - name: db
      port: 3306
    loadBalancerIP:
    selector:
      app: mysql-master-slave-${INSTANCE_NAME}
      deploymentconfig: mysql-slave-${INSTANCE_NAME}
  status:
    loadBalancer: {}
kind: Template
metadata:
  name: mysql-master-slave
  annotations:
    description: A MySQL Master/Slave deployment
parameters:
- name: INSTANCE_NAME
  description: The MySQL Master/Slave instance name
  required: true
- name: MYSQL_ROOT_PASSWORD
  description: The MySQL root password
  required: true
- name: MYSQL_DATABASE
  description: The MySQL database available from each instance
  value: mysqlmaster
- name: MYSQL_MASTER_PASSWORD
  description: The MySQL master user password
  value: password
- name: MYSQL_MASTER_USER
  description: The MySQL master user name
  value: master
- name: MYSQL_PASSWORD
  description: The MySQL user password
  value: password
- name: MYSQL_USER
  description: The MySQL user name
  value: user
