apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-storage
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  - ReadOnlyMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /nfs-storage
