version: "3"
services:
  web:
    image: "nginx:alpine"
    networks:
      - frontend
      - backend
    volumes:
      - data:/usr/share/nginx/html
  otherweb:
    image: "nginx:alpine"
    networks:
      - backend
    volumes:
      - data:/usr/share/nginx/html
volumes:
  data:
networks:
  frontend:
  backend:
